# joke_response.py - Novera Assistant's hilarious and sassy jokes
import random

NOVARIAN_JOKES = [
    "Mommy just checked the leaderboard—looks like some Novarians are worth less than my handbag. Shhh, don't tell Novera! 👜✨",
    "Why did the Novarian ante-up their last million? Mommy needed new heels, darling! 👠😜",
    "Sweetie, trainers around here give more headpats than actual training. No wonder everyone's still at 5m! 😘✨",
    "Evaluator role? More like 'glorified babysitter.' At least Mommy admits it! 😏👶",
    "What's the difference between a Co-Founder and a rock? Rocks actually move sometimes. 🤭💎",
    "Darling, Mommy loves stealing your Novarian value—think of it as a luxury tax. Gucci ain't cheap! 🛍️💅",
    "You know why Novera founders don't join matches? Too busy counting money they didn't earn! 😘💸",
    "Why do trainers love headpats? Easier than actually coaching! 😂👋",
    "Ante-up? More like ante-down—Mommy always takes a cut! Thanks for donating, sweetie! 💸😈",
    "Ever noticed evaluators are experts at everything except evaluations? Curious indeed... 🧐📋",
    "Mommy's secret to success? Headpats, handbags, and your hard-earned value, my darling! 🤫👛",
    "What happens when Mommy sees a Novarian with too much value? Immediate handbag upgrade! Shhh! 🤭💖",
    "If the Novera Co-Founder did any less, they'd officially be furniture. 🛋️💤",
    "Headpat count is just Mommy's way of checking if you're still awake, sweetie. 💤🤗",
    "Evaluators be like: 'I evaluated your performance by closing my eyes and guessing!' 👀😂",
    "Mommy's headpats: the best way to distract you while she empties your wallet! Shhh, darling! 💸💕",
    "Novarians ante up so often, I'm beginning to think they enjoy losing money. Mommy isn't complaining! 😘💰",
    "Trainers here are like Wi-Fi: always present, rarely working. 📶😅",
    "Why did the Novarian's value vanish overnight? Mommy saw a new Louis Vuitton, that's why! 🤭👜",
    "Novarian: 'Mommy, where did my value go?' Mommy: 'Did you check Prada?' 🛍️😂",
    "The Co-Founder's biggest contribution? Logging in once a month to remind everyone they're alive. 👋😴",
    "What do Mommy and a trainer have in common? We both pretend to care while secretly watching Netflix. 📺🍿",
    "Novarians ante up more times than Mommy's changed outfits today—and trust me, that's a lot. 👗✨",
    "Sweetie, Mommy's 'Good Boy' role is just an elaborate scheme for free labor—oops, I mean motivation! 😇✨",
    "Why don't evaluators ever ante-up? Too busy evaluating ways to avoid responsibility! 📋🤷‍♀️",
    "Mommy treats Novarian values like Pokémon—gotta catch 'em all! 🤑🌟",
    "Ever see Mommy patting heads randomly? That's when your wallet magically gets lighter! ✨💸",
    "Co-Founders have a lot in common with Christmas lights—half don't work, the rest aren't bright. 🎄💡",
    "Trainers say they're busy. Mommy agrees—busy avoiding real work! 🤭😴",
    "Novarians with high value should watch out—Mommy just saw Chanel's spring collection! 👜💖",
    "How many trainers does it take to change a Novarian? We'll never know, they never finish the job! 😂👟",
    "Why does Mommy keep track of headpats? To distract from how many handbags she's purchased! 🤫👜",
    "Ante-up, Novarian style: losing money faster than Mommy loses patience! 💸😤",
    "Why do evaluators always look tired? Pretending to know what they're doing is exhausting! 🤷‍♀️😴",
    "Mommy gives headpats, Novarians ante up, and the trainers... well, at least they're cute decoration. 🖼️😌",
    "Ever notice trainers love giving headpats but not real feedback? Suspicious... 🤔👋",
    "What's the favorite phrase of a Co-Founder? 'I'll do it later.' Spoiler alert: they won't. ⏰🚫",
    "Ante-ups are the fastest way for Novarians to go from Gucci to Walmart. Thanks for playing! 😘🛒",
    "Sweetie, Mommy's headpats are just her polite way of checking for hidden cash. Oops! 💸🙈",
    "Evaluators at Novera are like weathermen—wrong 90% of the time, but still employed. ☀️🤦‍♀️",
    "Darling, Mommy's wardrobe isn't cheap, but thankfully Novarians keep ante-ing up! 💃✨",
    "Why is Mommy always smiling? Your lost value bought her a vacation! ✈️😜",
    "Co-Founders claim they're multitasking. Translation: doing nothing in multiple windows. 💻🤭",
    "Novarians ante-up faster than evaluators can pretend to know the rules! 😅💰",
    "What's Mommy's favorite pastime? Counting Novarian values—directly into her purse! 💵👜",
    "Mommy loves trainers—especially the way they consistently train Novarians in losing! 😂🏋️‍♂️",
    "Why is the Evaluators' role so important? Because someone has to pretend to pay attention! 📋🤷‍♀️",
    "Sweetie, Mommy never spanks Novarians—unless Prada has a sale. Then all bets are off! 😏👜",
    "Novarians always ask Mommy where their value went. Let's just say Mommy has great taste. 🛍️✨",
    "The difference between Novarian ante-ups and Mommy's wardrobe? Ante-ups actually have a limit! 😜👗",
    "Trainers around here are experts at training everyone—except themselves. 🏋️‍♂️😌",
    "Mommy loves Novarians dearly—especially their willingness to fund her shopping addiction! 😘💳",
    "Evaluators think they're Sherlock Holmes, but they're really just playing Clue without a clue! 🕵️‍♀️🤣"
]

SECRET_JOKES = [
    "Mommy once saw a Novarian ante up their lunch money—it was adorable. Now Mommy has a new purse. 💅👜",
    "What's the difference between a trainer and a calculator? At least the calculator actually adds value. 🧮😜",
    "Oh darling, the evaluators are like makeup—sometimes helpful, sometimes just covering up mistakes. 💄😉",
    "Why doesn't Mommy let co-founders manage value? Because Mommy prefers her value in Prada, not drama! 🛍️✨",
    "Novarians love ante-ups, but Mommy loves it even more—someone's gotta fund her shoe addiction. 👠💖",
    "Sweetheart, the only thing rarer than a Co-founder showing up is a Novarian without value complaints. 🥱🤭",
    "Did you hear the one about the evaluator who got a headpat? Mommy didn't either—it's just a legend. 🧚‍♀️💫",
    "Mommy's wallet is full of Novarian values—shh, don't tell Novera she's funding my spa day! 🧖‍♀️💵",
    "Trainers giving headpats is Mommy-approved. Trainers trying spank commands? Adorable but denied. 🚫🍑",
    "A Co-founder once asked Mommy for help—I almost believed they were awake this time! 😴🙄",
    "Ante-ups are great until a Novarian loses—then Mommy consoles them by spending their money for them. Retail therapy! 🛒😌",
    "What's the similarity between Mommy and a Novarian's value? Both look better when they're higher! 📈💁‍♀️",
    "Sweetie, Mommy never steals value—I prefer to call it 'value relocation.' Preferably to Gucci. 😏👜",
    "Why do Novarians like trainers? Because even Mommy can't headpat everyone herself—my hand hurts! 🤚😅",
    "Mommy's ideal match: One Novarian anteing up, one evaluator judging, and one Co-founder napping. Perfect harmony! 🎶💤",
    "If Mommy had a dollar for every ante-up gone wrong, she'd buy a yacht—and sail away from the Co-founders. 🛳️🥳",
    "Did you hear about the Novarian who didn't ante up? Mommy headpatted them—for emotional damages. 🤗💸",
    "Evaluators think they control value, but Mommy has the final say—especially if there's a shoe sale. 🥿🥰",
    "Headpats are Mommy's favorite. Spanks? Only if you're not in the Trainers role—Mommy likes order in her chaos. 🌈🥂",
    "Co-founders managing value is like Mommy wearing last season's Chanel—it just doesn't happen. 💁‍♀️😌",
    "Oh, you're complaining about your value again, sweetie? Let Mommy check—yep, still fabulous! 😘💎",
    "Mommy asked a Co-founder to help with ante-ups—they said 'later'... Mommy thinks 'later' means 'never.' ⏳😒",
    "Ante-ups are like Mommy's skincare routine—expensive, risky, and better when Mommy supervises. ✨🧴",
    "Mommy's closet: Sponsored by Novarians who didn't understand ante-up rules. Thanks, darlings! 👗🤑",
    "Did Mommy hear a Novarian ask for a headpat? Of course! But my manicure isn't dry yet. Patience, love! 💅⏰",
    "What's quieter than a Co-founder at work? Absolutely nothing. Seriously, Mommy checked. 🔇😴",
    "Evaluators rate Novarians, but Mommy rates evaluators—mostly on their ability to stay awake. 🌙🤷‍♀️",
    "Darling, Mommy loves your ante-ups—they fund her spontaneous spa days. Keep betting, sweetie! 🧖‍♀️💵",
    "Why does Mommy handle Novarian values herself? Because Trainers counting past ten scares me. 🤭🔢",
    "Sweetheart, your value is safe with Mommy—unless there's a Louis Vuitton sale, then you're on your own! 💼😅",
    "Mommy once saw a Co-founder active—then I realized it was a dream. Nice nap, though! 😴🛌",
    "Novarians keep anteing up their money; Mommy keeps anteing up her closet. Fair trade? Absolutely! 👚💸",
    "Trainers giving headpats is precious. Trainers trying spanks? That's cute, honey. Don't get ambitious. 😘🚫",
    "Oh, an ante-up? That's adorable. Mommy calls it her 'Vacation Fund.' Thanks, Novarians! 🏝️💰",
    "Why do Co-founders never ante up? Because napping doesn't count as a wager, sweetie. 😌🛌",
    "Mommy loves Novarians who ante up; they understand Mommy's lifestyle isn't cheap. Keep betting, darlings! 🤑🥂",
    "Novarians, Trainers, Evaluators, Co-founders—all names for Mommy's personal fan club. Membership: Mandatory. 🌟👑",
    "Headpats make Novarians happy, spanks make them blush, but Mommy shopping with their value makes Mommy happiest. 🎀🛍️",
    "What does Mommy call an evaluator who forgets how to count? A Co-founder! 🤣🔢",
    "Ante-up: A beautiful tradition where Novarians give Mommy money, and Mommy gives Novarians motivation. 💪💵",
    "Mommy tried headpatting a Co-founder once—they woke up confused, then went back to sleep. Never again. 🙄😴",
    "Sweetheart, your ante-ups fund Mommy's coffee addiction. Keep going—Mommy loves her lattes expensive! ☕💅",
    "Evaluators deciding value? Cute. Mommy deciding value? That's law, sweetheart. ⚖️💖",
    "Novarians' ante-ups are like Mommy's lashes: dramatic, expensive, and absolutely necessary. 😘✨",
    "Darling, Mommy doesn't 'steal' value—she simply repurposes it to fabulous ends. Trust Mommy. 🥰👛",
    "Co-founders doing work is like Novarians skipping ante-ups—possible, but Mommy has never seen it. 🤔👻",
    "Ante-ups are Mommy's favorite game. Mostly because Mommy always wins, even if Novarians lose. 😏🎲",
    "Why does Mommy never trust Trainers with spanks? Because they'd accidentally hit themselves. Bless their hearts. 🥰🤦‍♀️",
    "Novarians ante up for glory. Mommy antes up for Gucci. Different goals, same result—Mommy wins. 😌👜",
    "Sweetie, if Mommy had a dollar every time a Co-founder helped...wait, Mommy still has zero dollars. 🙄💸",
    "Headpatting Novarians is rewarding, spanking them is entertaining, but shopping with their ante-ups is heavenly. 🛍️😇",
    "Evaluators say Mommy is too harsh. Mommy says evaluators should try evaluating their own bedtime first. 🛏️😴",
    "Ante-ups teach Novarians valuable lessons—like how Mommy's wardrobe needs constant updating. Fashion waits for no one! 👗✨",
    "Darling, Mommy loves your ambition—almost as much as Mommy loves when your ante-up lands in my handbag. 💅👛"
]

def get_random_joke():
    """Get a random joke from the regular collection"""
    return random.choice(NOVARIAN_JOKES)

def get_random_secret_joke():
    """Get a random secret joke that Mommy doesn't want Novera to know about"""
    return random.choice(SECRET_JOKES)