
"""Collection of playful responses for mute/unmute commands"""

MUTE_RESPONSES = [
    "Shhh... {member.mention} needs a little timeout to reflect on their behavior~ 🤫✋",
    "Time to be quiet, {member.mention}! Mommy's putting you in timeout~ 🔇💕",
    "Naughty boy {member.mention}, let's give those fingers a rest~ 🫦✨",
    "Someone's been too chatty! {member.mention}, enjoy your quiet time~ 🤐💝",
    "Mommy thinks {member.mention} needs to learn when to be silent~ 🍑✋",
    "No more talking for you, {member.mention}! Mommy's orders~ 😏🔕",
    "*places finger on lips* Hush now, {member.mention}~ 🫦💖",
    "Bad boys get muted, {member.mention}! Time for your punishment~ 😈🤫",
    "Somebody needs to learn some discipline~ {member.mention} 🎀🔇",
    "Be a good boy and stay quiet, {member.mention}! 💋✨",
    "Mommy's tired of your sass, {member.mention}! Time for silence~ 😤🤐",
    "No more back talk from you, {member.mention}! 🫦✋",
    "Shhh... good boys are seen, not heard~ Right, {member.mention}? 😏💕",
    "Time to zip those lips, {member.mention}! Mommy means business~ 🔇💝",
    "Someone's earned themselves a timeout~ {member.mention} 🍑✨",
    "*taps riding crop* Silence, {member.mention}! 😈🤫",
    "Quiet time for naughty {member.mention}~ 💖🔕",
    "No more words from you, {member.mention}! Just nods~ 😘🤐",
    "Behave yourself in silence, {member.mention}! 🎀✋",
    "Time to learn some manners quietly, {member.mention}~ 💋🔇",
    "Mommy's put {member.mention} in a timeout corner~ 😏✨",
    "Bad boys don't get speaking privileges, {member.mention}! 🍑🤫",
    "Shhhh... Let's have some quiet time, {member.mention}~ 💝🔕",
    "*stern look* Not another word, {member.mention}! 😠💖",
    "Time to practice being quiet, {member.mention}~ 🎀🤐",
    "Mommy's muted your sass, {member.mention}! 😈✋",
    "No talking back to Mommy, {member.mention}! 💋🔇",
    "Someone needs to learn to behave~ Right, {member.mention}? 😏💕",
    "Quiet time will do you good, {member.mention}~ 🍑✨",
    "Your chat privileges are mine now, {member.mention}! 💝🤫",
    "*wags finger* No more talking, {member.mention}! 😘🔕",
    "Be a good quiet boy for Mommy, {member.mention}~ 🎀✋",
    "Time to settle down in silence, {member.mention}! 💖🔇",
    "Mommy knows what's best - quiet time, {member.mention}! 😏✨",
    "Such a chatty boy... Time for silence, {member.mention}~ 🍑🤐",
    "Let's practice our quiet time, {member.mention}! 💝🔕",
    "*points to corner* Silence, {member.mention}! 😈💖",
    "No more words until Mommy says so, {member.mention}~ 🎀🤫",
    "Time to be a silent good boy, {member.mention}! 💋✋",
    "Quiet time with Mommy, {member.mention}~ 😏🔇",
    "Your voice is mine now, {member.mention}! 💕✨",
    "Hush, little one~ {member.mention} needs timeout~ 🍑🤐",
    "Bad boys lose their voice, {member.mention}! 💝🔕",
    "Mommy's putting you on mute, {member.mention}~ 😘✋",
    "Time to learn silence, {member.mention}! 🎀🔇",
    "No more chatter from you, {member.mention}~ 💖🤫",
    "Such a naughty talker, {member.mention}! 😏✨",
    "Quiet time starts now, {member.mention}! 🍑🔕",
    "Mommy says no more talking, {member.mention}~ 💝✋",
    "Silence is golden, {member.mention}! 💋🤐"
]

UNMUTE_RESPONSES = [
    "Welcome back to voice, {member.mention}~ Did you learn your lesson? 💋✨",
    "Mommy forgives you, {member.mention}. Be good now~ 🫂💕",
    "You can speak again, {member.mention}! Mommy hopes you'll behave~ 😘🎀",
    "Has {member.mention} learned to be a good boy now? 🐶💖",
    "Time for your voice back, {member.mention}~ Make Mommy proud~ 💝✨",
    "Mommy's letting you speak again, {member.mention}! Don't waste it~ 🫦💕",
    "Welcome back to chat, {member.mention}~ Mommy missed your voice~ 😊💫",
    "Timeout's over, {member.mention}! Show Mommy you've learned~ 🎀💝",
    "You can talk now, {member.mention}~ Make it worth Mommy's time~ 😘✨",
    "Mommy thinks you deserve your voice back, {member.mention}~ 💖🫂",
    "Be a good boy with your restored privileges, {member.mention}~ 🐶💕",
    "Time to hear that sweet voice again, {member.mention}! 💋✨",
    "Mommy's giving you another chance, {member.mention}~ 🫂💝",
    "Don't make Mommy regret this, {member.mention}~ 😏💫",
    "Welcome back to Mommy's good graces, {member.mention}! 🎀💖",
    "Your silence pleased Mommy, {member.mention}~ Here's your reward~ 😘✨",
    "Mommy thinks you've learned your lesson, {member.mention}~ 💕🫂",
    "Such a good quiet boy you were, {member.mention}! 🐶💝",
    "You may speak again, {member.mention}~ Make Mommy proud~ 💋💫",
    "Did the quiet time help you reflect, {member.mention}? 😊✨",
    "Mommy's favorite voice is back, {member.mention}~ 🎀💕",
    "You've earned your voice back, {member.mention}! 💖🫂",
    "Time to hear your sweet words again, {member.mention}~ 😘💝",
    "Mommy hopes you learned something, {member.mention}~ 🐶✨",
    "Welcome back to the conversation, {member.mention}! 💋💫",
    "Your quiet time is over, {member.mention}~ Be good~ 🫂💕",
    "Mommy missed hearing from you, {member.mention}~ 😊💖",
    "Show Mommy how well-behaved you can be, {member.mention}! 🎀💝",
    "Your voice is yours again, {member.mention}~ Use it wisely~ 😘✨",
    "Mommy's proud of your quiet time, {member.mention}~ 💕🫂",
    "Such a good patient boy, {member.mention}! 🐶💫",
    "You can speak freely now, {member.mention}~ 💋💝",
    "Mommy's giving you voice privileges again, {member.mention}~ 😊✨",
    "Welcome back to Mommy's good side, {member.mention}! 🎀💕",
    "Time to hear that voice again, {member.mention}~ 💖🫂",
    "You've served your quiet time well, {member.mention}~ 😘💝",
    "Mommy thinks you deserve to speak again, {member.mention}~ 🐶✨",
    "Use your voice wisely this time, {member.mention}! 💋💫",
    "Back to being Mommy's vocal boy, {member.mention}~ 🫂💕",
    "Your silence has earned you speech, {member.mention}~ 😊💖",
    "Mommy's lifting your quiet time, {member.mention}! 🎀💝",
    "Show me how well you can behave now, {member.mention}~ 😘✨",
    "Your voice is a privilege, {member.mention}~ Use it well~ 💕🫂",
    "Welcome back to speaking, {member.mention}! 🐶💫",
    "Mommy's ready to hear from you again, {member.mention}~ 💋💝",
    "You've earned back your voice, {member.mention}! 😊✨",
    "Be as good with words as you were in silence, {member.mention}~ 🎀💕",
    "Mommy's letting you speak again, {member.mention}~ 💖🫂",
    "Don't make Mommy mute you again, {member.mention}~ 😘💝",
    "Your timeout is over, {member.mention}! Make Mommy proud~ 🐶✨"
]
