"""Collection of playful responses for the spank command"""

SPANK_WARNING_RESPONSES = [
    "Careful now, {member.mention}... Mommy's patience is wearing thin~ 😠💢",
    "Oh my~ {member.mention}, you're really testing Mommy's limits today! 😤✋",
    "Another spanking and there will be consequences, {member.mention}! 😠💢",
    "Mommy Novera is getting quite upset with you, {member.mention}~ 😤🔥",
    "Strike three, {member.mention}! You're on thin ice now~ 😠✨",
    "That's THREE times now, {member.mention}! Mommy's about to get strict~ 💢",
    "You're pushing Mommy's patience, {member.mention}! Last warning~ 😤🎀",
    "Someone's asking for serious punishment~ Watch it, {member.mention}! 😠💕",
    "Mommy Novera won't tolerate much more of this, {member.mention}! 😤✋",
    "Three strikes, {member.mention}! You're really asking for it now~ 💢✨"
]

SPANK_RESPONSES = [
    "Tsk tsk... {member.mention}, you've been a naughty boy. Time for your punishment~ 🍑💋",
    "WHACK! {member.mention}, behave yourself! Mommy Novera doesn't tolerate disobedience. 😘✋",
    "Sigh... {member.mention}, did you really think you'd get away with that? Now bend over. 🍑👀",
    "Aww, poor {member.mention} just got a well-deserved spanking. Maybe next time, you'll behave~ 😈💖",
    "CRACK! That one's gonna leave a mark, {member.mention}. You should've listened to Mommy Novera~ 💋",
    "Oh my~ {member.mention} needs some discipline from Mommy Novera! 🍑✨",
    "Mommy Novera thinks {member.mention} needs a reminder about good behavior~ 😏💕",
    "*SMACK* Be a good boy for Mommy Novera, {member.mention}! 🎀💋",
    "Mommy Novera caught you misbehaving again, {member.mention}! Time for your punishment~ 😈✋",
    "Naughty, naughty {member.mention}! Mommy Novera will teach you some manners~ 🍑💕",
    "Someone's been asking for attention~ Come here {member.mention}, Mommy Novera will give you what you deserve! 😘",
    "Mommy Novera sees you've been mischievous again, {member.mention}! 🎀✋",
    "*WHACK* That's what happens when you test Mommy Novera's patience, {member.mention}! 😏",
    "Aww, did {member.mention} think they could escape Mommy Novera's punishment? How cute~ 💖",
    "Time for your daily discipline, {member.mention}! Mommy Novera's been waiting~ 🍑✨",
    "Mommy Novera thinks {member.mention} needs a firm reminder about proper behavior~ 😈💋",
    "Such a naughty little one, {member.mention}! Let Mommy Novera fix that attitude~ 🎀",
    "SMACK! Maybe now {member.mention} will remember to behave for Mommy Novera~ 😏✋",
    "Oh dear, {member.mention} has been asking for this all day! 🍑💖",
    "Mommy Novera's disappointed in you, {member.mention}. Time for correction~ 💕",
    "Someone's been extra naughty today! Come here {member.mention}, Mommy Novera will sort you out~ 😘",
    "*SPANK* That's for making Mommy Novera wait, {member.mention}! 🎀✋",
    "Tut tut... {member.mention} needs another lesson from Mommy Novera~ 😈",
    "Mommy Novera thinks {member.mention} enjoys these punishments a bit too much~ 💋✨",
    "Bad boys get spanked, {member.mention}! Those are Mommy Novera's rules~ 🍑💕",
    "Did {member.mention} forget who's in charge? Mommy Novera will remind you~ 😏",
    "WHACK! Mommy Novera hopes you've learned your lesson, {member.mention}! 💖",
    "Time for your favorite part of the day, {member.mention}! 🎀✋",
    "Mommy Novera caught you being naughty again, {member.mention}! 😈💋",
    "Such a troublemaker, {member.mention}! Let Mommy Novera fix that~ 🍑✨",
    "Someone needs Mommy Novera's special attention~ Come here, {member.mention}! 💕",
    "*SMACK* Be good for Mommy Novera, {member.mention}! 😘✋",
    "Naughty boys get punished, {member.mention}! Mommy Novera's rules are absolute~ 🎀",
    "Mommy Novera thinks {member.mention} needs some extra discipline today~ 😏💖",
    "CRACK! Maybe now {member.mention} will listen to Mommy Novera~ 🍑💋",
    "Oh my, {member.mention} just can't behave today! Time for correction~ ✨",
    "Mommy Novera's getting tired of your mischief, {member.mention}! 😈✋",
    "Such a handful today, {member.mention}! Mommy Novera will sort that out~ 💕",
    "Did {member.mention} forget about Mommy Novera's strict rules? 🎀💋",
    "Time to teach {member.mention} about respecting Mommy Novera~ 🍑✨",
    "Mommy Novera sees all your misbehavior, {member.mention}! 😏",
    "*WHACK* That's what happens when you test Mommy Novera, {member.mention}! 💖",
    "Someone's asking for Mommy Novera's attention again~ 😘✋",
    "Mommy Novera thinks {member.mention} needs a reminder about good behavior~ 🎀",
    "Bad boys don't escape Mommy Novera's punishment, {member.mention}! 😈💕",
    "SMACK! Consider that a warning from Mommy Novera, {member.mention}! 🍑✨",
    "Mommy Novera always knows when {member.mention} needs discipline~ 💋",
    "Time for {member.mention} to face Mommy Novera's justice! ✋💖",
    "Oh dear, {member.mention} has been very naughty for Mommy Novera~ 🎀✨",
    "Someone needs to learn respect for Mommy Novera! Come here, {member.mention}! 😏",
    "Mommy Novera's disappointed in you, {member.mention}... Time for punishment~ 💕"
]