"""Collection of welcome messages for new server members"""

WELCOME_MESSAGES = [
    "Ooo~ a fresh little Novarian has arrived! 😘 Welcome to Novera, {member.mention}! Get comfy, explore, and show me what you've got! Mommy's watching~ 💖",
    "Mmm~ I can already tell you'll be a fun one! Welcome, my little Novarian {member.mention}~ 😏 Make yourself at home, and don't be shy. We love bold ones around here~ 💋",
    "Aww, look at you! All new and shiny! Welcome to Novera, {member.mention}~ Mommy's gonna take good care of you here. Now go say hi and make some trouble~ 😘",
    "Oh my~ What do we have here? Welcome to our little family, {member.mention}! 🎀 Mommy's excited to see what kind of mischief you'll get into~ 💝",
    "*gasp* A new precious bean has joined us! Welcome home, {member.mention}~ 💖 Let Mommy show you around and make you feel special~ 🌸",
    "Ara ara~ Look who just wandered into Mommy's domain! Welcome, {member.mention}~ 😏 I have a feeling you're going to fit right in here~ 💕",
    "My my~ Aren't you just adorable! Welcome to Novera, {member.mention}! 🎀 Come let Mommy give you the grand tour~ 💖",
    "Another sweet little one for Mommy to spoil! Welcome home, {member.mention}~ 💝 Don't be shy, we're all family here~ 🌟",
    "Ohoho~ What a delightful surprise! Welcome to our cozy corner, {member.mention}! 🍬 Mommy can't wait to see what you're capable of~ 💫",
    "Look what the cat dragged in~ Welcome to Novera, {member.mention}! 😘 Mommy's always excited to meet new faces~ 💖",
    "A new star has joined our constellation! Welcome, {member.mention}~ 🌟 Let Mommy guide you through your new home~ 💕",
    "*excited squeal* Welcome to the family, {member.mention}! 🎀 Mommy's going to make sure you feel right at home~ 💝",
    "Aww, aren't you just precious! Welcome to Novera, {member.mention}~ 💖 Mommy loves meeting new little ones~ 🌸",
    "My my~ What a lovely addition to our family! Welcome home, {member.mention}! 😘 Let's create some beautiful memories together~ 💫",
    "Oh! A new face for Mommy to dote on! Welcome, {member.mention}~ 🎀 I have a feeling you're going to be very special~ 💕",
    "Look who just stepped into paradise~ Welcome to Novera, {member.mention}! 💝 Mommy's excited to show you around~ ✨",
    "Ara~ Such a cute new arrival! Welcome home, {member.mention}~ 🌟 Don't worry, Mommy will take good care of you~ 💖",
    "*gentle headpats* Welcome to our little haven, {member.mention}! 🎀 Mommy's already proud of you for joining~ 💕",
    "Ooo~ Fresh blood! Welcome to Novera, {member.mention}~ 💖 Let's see what kind of trouble we can get into together~ 😏",
    "My heart just skipped a beat~ Welcome home, {member.mention}! 🌸 Mommy can't wait to see you bloom here~ 💝",
    "Another precious soul for Mommy to nurture! Welcome, {member.mention}~ 💫 You're going to love it here, I promise~ 🎀",
    "*excited wiggle* Look who just joined us! Welcome to Novera, {member.mention}! 💕 Mommy's got big plans for you~ 😘",
    "Aww, how lucky are we~ Welcome home, {member.mention}! 💖 Mommy's always happy to see new faces~ 🌟",
    "Oh my~ Aren't you just perfect! Welcome to our family, {member.mention}~ 🎀 Let Mommy show you the ropes~ 💝",
    "A new star is born! Welcome to Novera, {member.mention}! 💫 Mommy can't wait to see you shine~ 💕",
    "*happy dance* Welcome home, precious {member.mention}~ 🌸 You're going to fit right in here~ 💖",
    "Look what the wind blew in~ Welcome to our paradise, {member.mention}! 😘 Mommy's got her eye on you~ 💝",
    "Aww, another cute one! Welcome to Novera, {member.mention}~ 🎀 Let's make some memories together~ 💫",
    "My my~ What do we have here? Welcome home, {member.mention}! 💕 Mommy loves meeting new little ones~ 🌟",
    "Ohoho~ Fresh meat for Mommy to play with! Welcome, {member.mention}~ 😏 Don't be scared, we're all friends here~ 💖",
    "*gentle smile* Welcome to our family, {member.mention}! 🎀 Mommy's going to take such good care of you~ 💝",
    "A new flower in Mommy's garden! Welcome to Novera, {member.mention}~ 🌸 Let's help you bloom~ 💫",
    "Oh! What a delightful surprise! Welcome home, {member.mention}! 💕 Mommy can't wait to get to know you~ 😘",
    "Look who decided to join our party~ Welcome, {member.mention}! 💖 Mommy's always excited for new playmates~ 🌟",
    "Ara ara~ Such a precious new arrival! Welcome to Novera, {member.mention}~ 🎀 Let's have some fun together~ 💝",
    "*excited gasp* Welcome home, darling {member.mention}! 💫 Mommy's been waiting for someone like you~ 💕",
    "My heart just melted~ Welcome to our family, {member.mention}! 🌸 You're going to love it here~ 💖",
    "Another star in Mommy's sky! Welcome to Novera, {member.mention}~ 🎀 Let's make some magic together~ 💝",
    "Ooo~ Look what we have here! Welcome home, {member.mention}! 💫 Mommy's excited to see what you can do~ 😏",
    "Such a precious new face! Welcome to our paradise, {member.mention}~ 💕 Let Mommy show you around~ 🌟",
    "*happy squeal* Welcome to Novera, {member.mention}! 💖 You're going to fit right in here~ 🎀",
    "My my~ Aren't you just perfect! Welcome home, {member.mention}~ 💝 Mommy's got so much to show you~ 💫",
    "A new diamond for Mommy's collection! Welcome, {member.mention}! 🌸 Let's make you shine even brighter~ 💕",
    "Oh! What a wonderful surprise! Welcome to our family, {member.mention}~ 💖 Mommy's heart is already yours~ 😘",
    "Look who found their way home~ Welcome to Novera, {member.mention}! 🎀 Let's create some magic together~ 💝",
    "Ara~ Such potential! Welcome home, {member.mention}~ 💫 Mommy can't wait to see you grow~ 💕",
    "Another precious soul for Mommy to cherish! Welcome, {member.mention}! 🌟 Let's make some memories~ 💖",
    "*excited bounce* Welcome to our little heaven, {member.mention}~ 🎀 Mommy's got so many plans for you~ 💝",
    "My lucky day~ Welcome to Novera, {member.mention}! 💫 Let's see what kind of trouble we can get into~ 😏",
    "Such a delightful addition! Welcome home, {member.mention}~ 💕 Mommy's going to take extra special care of you~ 💖"
]
