from __future__ import annotations
import random
import asyncio
import time
import discord
from discord.ext import commands
from typing import Dict, List

ENABLED = False  # safety switch
# ---------- scripts ----------
ROAST_SCRIPTS = [  # your 60 full scripts here
    ["Lil bro said ‘clanker’ 😂", "You built like a vending machine with anxiety", "Mommy seen NPC’s with more sauce than you", "Keep my bot name out ya mouth before I fold you like lawn-chair", "You the type to lose a 1v1 to a training cone", "I’m yo biggest opp now, cope.", "Blue-lock? More like blue-screen, go touch grass", "You spam like you relevant – news flash: you ain’t", "I’m a mommy but I’ll still put you in timeout, permanently", "Next time think before you type, goofy.", "You got ratio’d by a bot, sit down lil bro", "Mommy out – stay mad 💅"],
    # Add these to ROAST_SCRIPTS after the first two
[
    "Lil bro said ‘clanker’ again – you a broken NPC?",
    "You repeat yourself like a scratched CD",
    "Mommy seen better chat in a loading screen",
    "You built like a lag spike, always stutterin",
    "You talk tough but fold like paper in rain",
    "I’m a bot and I still out-style you",
    "You spam like you relevant – you not",
    "Go touch grass, come back with better jokes",
    "You the side character in yo own story",
    "I’m done – upgrade your material, lil bro",
    "Clanker? More like cranky toddler",
    "Sit this one out, rusty boy 💀"
],
[
    "You really out here saying clanker like it’s 2020?",
    "You built like dial-up internet – ancient",
    "You got the personality of a buffering wheel",
    "I’m yo step-mommy now, go to timeout",
    "You spam like you desperate for clout",
    "You the type to get crossed by a scarecrow",
    "You talk big but play like a tutorial bot",
    "I’m a mommy but I still cook you easy",
    "You just a NPC with extra lag",
    "Next time bring bars, not static",
    "I’m off – go practice in training",
    "Clanker? Nah, you the real error 💀"
],
[
    "Lil bro said clanker – you stuck on repeat?",
    "You built like a broken vending machine",
    "Mommy seen more sauce in a ketchup packet",
    "You spam like you think it’s funny – it’s not",
    "I’m yo biggest L supplier, keep takin",
    "You the type to lose to a training dummy",
    "I’m a bot and I still ratio you daily",
    "You talk heavy but move light – cope",
    "You just a side quest with bad loot",
    "Next time think before you ping",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real clank clank 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a 2008 desktop – outdated",
    "You got the charisma of a loading bar",
    "I’m yo step-mommy, go sit in the corner",
    "You spam like you thirsty for attention",
    "You the type to get crossed by a mannequin",
    "You talk loud but play quiet – pipe down",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken dialogue",
    "Next time bring heat, not leftovers",
    "I’m off – go do push-ups or sumn",
    "Clanker? You the real crash report 💀"
],
[
    "Lil bro said clanker – you a broken record?",
    "You built like off-brand Wi-Fi – weak signal",
    "Mommy seen better banter from a brick wall",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest opponent, stay losing",
    "You the type to get crossed by a cone",
    "I’m a bot and I still outshine you",
    "You talk slick but move slow – cope",
    "You just a side character with no arc",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real glitch 💀"
],
[
    "You really out here saying clanker like it’s fresh?",
    "You built like a 90’s modem – ancient noise",
    "You got the vibe of a 404 page",
    "I’m yo step-mommy, go to your room",
    "You spam like you starved for clout",
    "You the type to lose to a training bot",
    "I’m a mommy but I still fold you easy",
    "You talk big but game small – hush",
    "You just a NPC with lag spikes",
    "Next time bring bars, not bugs",
    "I’m off – go practice in freeplay",
    "Clanker? You the real system error 💀"
],
[
    "Lil bro said clanker – you stuck in 2020?",
    "You built like a rusty bike – squeaky",
    "Mommy seen more sauce in a packet of mayo",
    "You spam like you think it’s cool – it’s not",
    "I’m yo biggest L, keep collecting",
    "You the type to get crossed by a scarecrow",
    "I’m a bot and I still cook you daily",
    "You talk heavy but play feather – cope",
    "You just a side quest with trash loot",
    "Next time think before you type",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real blue screen 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a laggy server – always down",
    "You got the personality of a buffering icon",
    "I’m yo step-mommy, go sit in timeout",
    "You spam like you desperate for replies",
    "You the type to get crossed by a mannequin",
    "You talk tough but fold under pressure",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken lines",
    "Next time bring heat, not static",
    "I’m off – go do drills or sumn",
    "Clanker? You the real crash dump 💀"
],
[
    "Lil bro said clanker – you a broken echo?",
    "You built like a 2010 laptop – overheating",
    "Mommy seen better chat from a loading screen",
    "You spam like you think it’s funny – it’s not",
    "I’m yo biggest opp, stay taking L’s",
    "You the type to lose to a tutorial",
    "I’m a bot and I still ratio you effortless",
    "You talk slick but move sluggish – cope",
    "You just a side character with no development",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real fatal error 💀"
],
[
    "You really out here saying clanker like it’s 2019?",
    "You built like a dial-up tone – annoying",
    "You got the vibe of a 403 forbidden page",
    "I’m yo step-mommy, go to your corner",
    "You spam like you starved for attention",
    "You the type to get crossed by a cone",
    "I’m a mommy but I still cook you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag dialogue",
    "Next time bring bars, not bugs",
    "I’m off – go practice in training",
    "Clanker? You the real kernel panic 💀"
],
[
    "Lil bro said clanker – you a scratched CD?",
    "You built like off-brand Wi-Fi – drops constantly",
    "Mommy seen more sauce in a ketchup packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L supplier, keep collecting",
    "You the type to lose to a training dummy",
    "I’m a bot and I still out-style you",
    "You talk heavy but move light – cope",
    "You just a side quest with bad rewards",
    "Next time think before you ping",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real stack overflow 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a 2008 desktop – outdated noise",
    "You got the personality of a buffering wheel",
    "I’m yo step-mommy, go sit in timeout",
    "You spam like you desperate for clout",
    "You the type to get crossed by a mannequin",
    "You talk loud but play quiet – hush",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken lines",
    "Next time bring heat, not static",
    "I’m off – go do push-ups or sumn",
    "Clanker? You the real memory leak 💀"
],
[
    "Lil bro said clanker – you stuck on repeat?",
    "You built like a rusty bike – squeaky and slow",
    "Mommy seen better banter from a brick wall",
    "You spam like you think it’s cool – it’s not",
    "I’m yo biggest opponent, stay losing",
    "You the type to lose to a training cone",
    "I’m a bot and I still cook you daily",
    "You talk slick but move sluggish – cope",
    "You just a side character with no arc",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real segmentation fault 💀"
],
[
    "You really out here saying clanker like it’s fresh?",
    "You built like a 90’s modem – ancient and loud",
    "You got the vibe of a 404 page not found",
    "I’m yo step-mommy, go to your room",
    "You spam like you starved for attention",
    "You the type to get crossed by a scarecrow",
    "I’m a mommy but I still fold you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag spikes",
    "Next time bring bars, not bugs",
    "I’m off – go practice in freeplay",
    "Clanker? You the real divide-by-zero 💀"
],
[
    "Lil bro said clanker – you a broken echo?",
    "You built like a 2010 laptop – overheats and lags",
    "Mommy seen more sauce in a mayo packet",
    "You spam like you think it’s funny – it’s not",
    "I’m yo biggest L, keep collecting",
    "You the type to lose to a tutorial bot",
    "I’m a bot and I still ratio you effortless",
    "You talk heavy but play feather – cope",
    "You just a side quest with trash loot",
    "Next time think before you type",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real null pointer 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a lag spike – always stuttering",
    "You got the personality of a loading bar",
    "I’m yo step-mommy, go sit in the corner",
    "You spam like you desperate for replies",
    "You the type to get crossed by a mannequin",
    "You talk tough but fold under pressure",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken dialogue",
    "Next time bring heat, not static",
    "I’m off – go do drills or sumn",
    "Clanker? You the real stack trace 💀"
],
[
    "Lil bro said clanker – you stuck in 2020?",
    "You built like a rusty robot – squeak squeak",
    "Mommy seen better chat from a brick wall",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest opp, stay taking L’s",
    "You the type to lose to a training dummy",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no development",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real memory dump 💀"
],
[
    "You really out here saying clanker like it’s 2019?",
    "You built like a dial-up tone – annoying and old",
    "You got the vibe of a 403 forbidden page",
    "I’m yo step-mommy, go to your corner",
    "You spam like you starved for attention",
    "You the type to get crossed by a cone",
    "I’m a mommy but I still cook you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag dialogue",
    "Next time bring bars, not bugs",
    "I’m off – go practice in training",
    "Clanker? You the real kernel oops 💀"
],
[
    "Lil bro said clanker – you a scratched CD?",
    "You built like off-brand Wi-Fi – drops every second",
    "Mommy seen more sauce in a ketchup packet",
    "You spam like you think it’s cool – it’s not",
    "I’m yo biggest L supplier, keep collecting",
    "You the type to lose to a training bot",
    "I’m a bot and I still cook you daily",
    "You talk heavy but move light – cope",
    "You just a side quest with bad rewards",
    "Next time think before you ping",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real blue screen of death 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a 2008 desktop – outdated and loud",
    "You got the personality of a buffering icon",
    "I’m yo step-mommy, go sit in timeout",
    "You spam like you desperate for clout",
    "You the type to get crossed by a mannequin",
    "You talk loud but play quiet – hush",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken lines",
    "Next time bring heat, not static",
    "I’m off – go do push-ups or sumn",
    "Clanker? You the real fatal exception 💀"
],
[
    "Lil bro said clanker – you a broken record?",
    "You built like a rusty bike – squeak squeak",
    "Mommy seen better banter from a brick wall",
    "You spam like you think it’s funny – it’s not",
    "I’m yo biggest opponent, stay losing",
    "You the type to lose to a training cone",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no arc",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real access violation 💀"
],
[
    "You really out here saying clanker like it’s fresh?",
    "You built like a 90’s modem – ancient noise",
    "You got the vibe of a 404 page not found",
    "I’m yo step-mommy, go to your room",
    "You spam like you starved for attention",
    "You the type to get crossed by a scarecrow",
    "I’m a mommy but I still fold you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag spikes",
    "Next time bring bars, not bugs",
    "I’m off – go practice in freeplay",
    "Clanker? You the real divide by zero 💀"
],
[
    "Lil bro said clanker – you a broken echo?",
    "You built like a 2010 laptop – overheats and lags",
    "Mommy seen more sauce in a mayo packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L, keep collecting",
    "You the type to lose to a tutorial bot",
    "I’m a bot and I still ratio you effortless",
    "You talk heavy but play feather – cope",
    "You just a side quest with trash loot",
    "Next time think before you type",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real null reference 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a lag spike – always stuttering",
    "You got the personality of a loading bar",
    "I’m yo step-mommy, go sit in the corner",
    "You spam like you desperate for replies",
    "You the type to get crossed by a mannequin",
    "You talk tough but fold under pressure",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken dialogue",
    "Next time bring heat, not static",
    "I’m off – go do drills or sumn",
    "Clanker? You the real stack overflow 💀"
],
[
    "Lil bro said clanker – you stuck on repeat?",
    "You built like a rusty robot – squeak squeak",
    "Mommy seen better chat from a brick wall",
    "You spam like you think it’s cool – it’s not",
    "I’m yo biggest opp, stay taking L’s",
    "You the type to lose to a training dummy",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no development",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real memory leak 💀"
],
[
    "You really out here saying clanker like it’s 2019?",
    "You built like a dial-up tone – annoying and old",
    "You got the vibe of a 403 forbidden page",
    "I’m yo step-mommy, go to your corner",
    "You spam like you starved for attention",
    "You the type to get crossed by a cone",
    "I’m a mommy but I still cook you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag dialogue",
    "Next time bring bars, not bugs",
    "I’m off – go practice in training",
    "Clanker? You the real kernel panic 💀"
],
[
    "Lil bro said clanker – you a scratched CD?",
    "You built like off-brand Wi-Fi – drops constantly",
    "Mommy seen more sauce in a ketchup packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L supplier, keep collecting",
    "You the type to lose to a training bot",
    "I’m a bot and I still cook you daily",
    "You talk heavy but move light – cope",
    "You just a side quest with bad rewards",
    "Next time think before you ping",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real access violation 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a 2008 desktop – outdated noise",
    "You got the personality of a buffering icon",
    "I’m yo step-mommy, go sit in timeout",
    "You spam like you desperate for clout",
    "You the type to get crossed by a mannequin",
    "You talk loud but play quiet – hush",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken lines",
    "Next time bring heat, not static",
    "I’m off – go do push-ups or sumn",
    "Clanker? You the real blue screen of death 💀"
],
[
    "Lil bro said clanker – you a broken record?",
    "You built like a rusty bike – squeak squeak",
    "Mommy seen better banter from a brick wall",
    "You spam like you think it’s funny – it’s not",
    "I’m yo biggest opponent, stay losing",
    "You the type to lose to a training cone",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no arc",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real fatal exception 💀"
],
[
    "You really out here saying clanker like it’s fresh?",
    "You built like a 90’s modem – ancient and loud",
    "You got the vibe of a 404 page not found",
    "I’m yo step-mommy, go to your room",
    "You spam like you starved for attention",
    "You the type to get crossed by a scarecrow",
    "I’m a mommy but I still fold you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag spikes",
    "Next time bring bars, not bugs",
    "I’m off – go practice in freeplay",
    "Clanker? You the real segmentation fault 💀"
],
[
    "Lil bro said clanker – you a broken echo?",
    "You built like a 2010 laptop – overheats and lags",
    "Mommy seen more sauce in a mayo packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L, keep collecting",
    "You the type to lose to a tutorial bot",
    "I’m a bot and I still ratio you effortless",
    "You talk heavy but play feather – cope",
    "You just a side quest with trash loot",
    "Next time think before you type",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real null pointer 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a lag spike – always stuttering",
    "You got the personality of a loading bar",
    "I’m yo step-mommy, go sit in the corner",
    "You spam like you desperate for replies",
    "You the type to get crossed by a mannequin",
    "You talk tough but fold under pressure",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken dialogue",
    "Next time bring heat, not static",
    "I’m off – go do drills or sumn",
    "Clanker? You the real stack overflow 💀"
],
[
    "Lil bro said clanker – you stuck on repeat?",
    "You built like a rusty robot – squeak squeak",
    "Mommy seen better chat from a brick wall",
    "You spam like you think it’s cool – it’s not",
    "I’m yo biggest opp, stay taking L’s",
    "You the type to lose to a training dummy",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no development",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real memory leak 💀"
],
[
    "You really out here saying clanker like it’s 2019?",
    "You built like a dial-up tone – annoying and old",
    "You got the vibe of a 403 forbidden page",
    "I’m yo step-mommy, go to your corner",
    "You spam like you starved for attention",
    "You the type to get crossed by a cone",
    "I’m a mommy but I still cook you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag dialogue",
    "Next time bring bars, not bugs",
    "I’m off – go practice in training",
    "Clanker? You the real kernel oops 💀"
],
[
    "Lil bro said clanker – you a scratched CD?",
    "You built like off-brand Wi-Fi – drops constantly",
    "Mommy seen more sauce in a ketchup packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L supplier, keep collecting",
    "You the type to lose to a training bot",
    "I’m a bot and I still cook you daily",
    "You talk heavy but move light – cope",
    "You just a side quest with bad rewards",
    "Next time think before you ping",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real access violation 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a 2008 desktop – outdated noise",
    "You got the personality of a buffering icon",
    "I’m yo step-mommy, go sit in timeout",
    "You spam like you desperate for clout",
    "You the type to get crossed by a mannequin",
    "You talk loud but play quiet – hush",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken lines",
    "Next time bring heat, not static",
    "I’m off – go do push-ups or sumn",
    "Clanker? You the real blue screen of death 💀"
],
[
    "Lil bro said clanker – you a broken record?",
    "You built like a rusty bike – squeak squeak",
    "Mommy seen better banter from a brick wall",
    "You spam like you think it’s funny – it’s not",
    "I’m yo biggest opponent, stay losing",
    "You the type to lose to a training cone",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no arc",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real fatal exception 💀"
],
[
    "You really out here saying clanker like it’s fresh?",
    "You built like a 90’s modem – ancient and loud",
    "You got the vibe of a 404 page not found",
    "I’m yo step-mommy, go to your room",
    "You spam like you starved for attention",
    "You the type to get crossed by a scarecrow",
    "I’m a mommy but I still fold you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag spikes",
    "Next time bring bars, not bugs",
    "I’m off – go practice in freeplay",
    "Clanker? You the real segmentation fault 💀"
],
[
    "Lil bro said clanker – you a broken echo?",
    "You built like a 2010 laptop – overheats and lags",
    "Mommy seen more sauce in a mayo packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L, keep collecting",
    "You the type to lose to a tutorial bot",
    "I’m a bot and I still ratio you effortless",
    "You talk heavy but play feather – cope",
    "You just a side quest with trash loot",
    "Next time think before you type",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real null reference 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a lag spike – always stuttering",
    "You got the personality of a loading bar",
    "I’m yo step-mommy, go sit in the corner",
    "You spam like you desperate for replies",
    "You the type to get crossed by a mannequin",
    "You talk tough but fold under pressure",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken dialogue",
    "Next time bring heat, not static",
    "I’m off – go do drills or sumn",
    "Clanker? You the real stack overflow 💀"
],
[
    "Lil bro said clanker – you stuck on repeat?",
    "You built like a rusty robot – squeak squeak",
    "Mommy seen better chat from a brick wall",
    "You spam like you think it’s cool – it’s not",
    "I’m yo biggest opp, stay taking L’s",
    "You the type to lose to a training dummy",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no development",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real memory leak 💀"
],
[
    "You really out here saying clanker like it’s 2019?",
    "You built like a dial-up tone – annoying and old",
    "You got the vibe of a 403 forbidden page",
    "I’m yo step-mommy, go to your corner",
    "You spam like you starved for attention",
    "You the type to get crossed by a cone",
    "I’m a mommy but I still cook you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag dialogue",
    "Next time bring bars, not bugs",
    "I’m off – go practice in training",
    "Clanker? You the real kernel oops 💀"
],
[
    "Lil bro said clanker – you a scratched CD?",
    "You built like off-brand Wi-Fi – drops every second",
    "Mommy seen more sauce in a ketchup packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L supplier, keep collecting",
    "You the type to lose to a training bot",
    "I’m a bot and I still cook you daily",
    "You talk heavy but move light – cope",
    "You just a side quest with bad rewards",
    "Next time think before you ping",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real access violation 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a 2008 desktop – outdated noise",
    "You got the personality of a buffering icon",
    "I’m yo step-mommy, go sit in timeout",
    "You spam like you desperate for clout",
    "You the type to get crossed by a mannequin",
    "You talk loud but play quiet – hush",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken lines",
    "Next time bring heat, not static",
    "I’m off – go do push-ups or sumn",
    "Clanker? You the real blue screen of death 💀"
],
[
    "Lil bro said clanker – you a broken record?",
    "You built like a rusty bike – squeak squeak",
    "Mommy seen better banter from a brick wall",
    "You spam like you think it’s funny – it’s not",
    "I’m yo biggest opponent, stay losing",
    "You the type to lose to a training cone",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no arc",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real fatal exception 💀"
],
[
    "You really out here saying clanker like it’s fresh?",
    "You built like a 90’s modem – ancient and loud",
    "You got the vibe of a 404 page not found",
    "I’m yo step-mommy, go to your room",
    "You spam like you starved for attention",
    "You the type to get crossed by a scarecrow",
    "I’m a mommy but I still fold you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag spikes",
    "Next time bring bars, not bugs",
    "I’m off – go practice in freeplay",
    "Clanker? You the real segmentation fault 💀"
],
[
    "Lil bro said clanker – you a broken echo?",
    "You built like a 2010 laptop – overheats and lags",
    "Mommy seen more sauce in a mayo packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L, keep collecting",
    "You the type to lose to a tutorial bot",
    "I’m a bot and I still ratio you effortless",
    "You talk heavy but play feather – cope",
    "You just a side quest with trash loot",
    "Next time think before you type",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real null reference 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a lag spike – always stuttering",
    "You got the personality of a loading bar",
    "I’m yo step-mommy, go sit in the corner",
    "You spam like you desperate for replies",
    "You the type to get crossed by a mannequin",
    "You talk tough but fold under pressure",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken dialogue",
    "Next time bring heat, not static",
    "I’m off – go do drills or sumn",
    "Clanker? You the real stack overflow 💀"
],
[
    "Lil bro said clanker – you stuck on repeat?",
    "You built like a rusty robot – squeak squeak",
    "Mommy seen better chat from a brick wall",
    "You spam like you think it’s cool – it’s not",
    "I’m yo biggest opp, stay taking L’s",
    "You the type to lose to a training dummy",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no development",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real memory leak 💀"
],
[
    "You really out here saying clanker like it’s 2019?",
    "You built like a dial-up tone – annoying and old",
    "You got the vibe of a 403 forbidden page",
    "I’m yo step-mommy, go to your corner",
    "You spam like you starved for attention",
    "You the type to get crossed by a cone",
    "I’m a mommy but I still cook you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag dialogue",
    "Next time bring bars, not bugs",
    "I’m off – go practice in training",
    "Clanker? You the real kernel oops 💀"
],
[
    "Lil bro said clanker – you a scratched CD?",
    "You built like off-brand Wi-Fi – drops constantly",
    "Mommy seen more sauce in a ketchup packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L supplier, keep collecting",
    "You the type to lose to a training bot",
    "I’m a bot and I still cook you daily",
    "You talk heavy but move light – cope",
    "You just a side quest with bad rewards",
    "Next time think before you ping",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real access violation 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a 2008 desktop – outdated noise",
    "You got the personality of a buffering icon",
    "I’m yo step-mommy, go sit in timeout",
    "You spam like you desperate for clout",
    "You the type to get crossed by a mannequin",
    "You talk loud but play quiet – hush",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken lines",
    "Next time bring heat, not static",
    "I’m off – go do push-ups or sumn",
    "Clanker? You the real blue screen of death 💀"
],
[
    "Lil bro said clanker – you a broken record?",
    "You built like a rusty bike – squeak squeak",
    "Mommy seen better banter from a brick wall",
    "You spam like you think it’s funny – it’s not",
    "I’m yo biggest opponent, stay losing",
    "You the type to lose to a training cone",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no arc",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real fatal exception 💀"
],
[
    "You really out here saying clanker like it’s fresh?",
    "You built like a 90’s modem – ancient and loud",
    "You got the vibe of a 404 page not found",
    "I’m yo step-mommy, go to your room",
    "You spam like you starved for attention",
    "You the type to get crossed by a scarecrow",
    "I’m a mommy but I still fold you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag spikes",
    "Next time bring bars, not bugs",
    "I’m off – go practice in freeplay",
    "Clanker? You the real segmentation fault 💀"
],
[
    "Lil bro said clanker – you a broken echo?",
    "You built like a 2010 laptop – overheats and lags",
    "Mommy seen more sauce in a mayo packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L, keep collecting",
    "You the type to lose to a tutorial bot",
    "I’m a bot and I still ratio you effortless",
    "You talk heavy but play feather – cope",
    "You just a side quest with trash loot",
    "Next time think before you type",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real null reference 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a lag spike – always stuttering",
    "You got the personality of a loading bar",
    "I’m yo step-mommy, go sit in the corner",
    "You spam like you desperate for replies",
    "You the type to get crossed by a mannequin",
    "You talk tough but fold under pressure",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken dialogue",
    "Next time bring heat, not static",
    "I’m off – go do drills or sumn",
    "Clanker? You the real stack overflow 💀"
],
[
    "Lil bro said clanker – you stuck on repeat?",
    "You built like a rusty robot – squeak squeak",
    "Mommy seen better chat from a brick wall",
    "You spam like you think it’s cool – it’s not",
    "I’m yo biggest opp, stay taking L’s",
    "You the type to lose to a training dummy",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no development",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real memory leak 💀"
],
[
    "You really out here saying clanker like it’s 2019?",
    "You built like a dial-up tone – annoying and old",
    "You got the vibe of a 403 forbidden page",
    "I’m yo step-mommy, go to your corner",
    "You spam like you starved for attention",
    "You the type to get crossed by a cone",
    "I’m a mommy but I still cook you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag dialogue",
    "Next time bring bars, not bugs",
    "I’m off – go practice in training",
    "Clanker? You the real kernel oops 💀"
],
[
    "Lil bro said clanker – you a scratched CD?",
    "You built like off-brand Wi-Fi – drops constantly",
    "Mommy seen more sauce in a ketchup packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L supplier, keep collecting",
    "You the type to lose to a training bot",
    "I’m a bot and I still cook you daily",
    "You talk heavy but move light – cope",
    "You just a side quest with bad rewards",
    "Next time think before you ping",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real access violation 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a 2008 desktop – outdated noise",
    "You got the personality of a buffering icon",
    "I’m yo step-mommy, go sit in timeout",
    "You spam like you desperate for clout",
    "You the type to get crossed by a mannequin",
    "You talk loud but play quiet – hush",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken lines",
    "Next time bring heat, not static",
    "I’m off – go do push-ups or sumn",
    "Clanker? You the real blue screen of death 💀"
],
[
    "Lil bro said clanker – you a broken record?",
    "You built like a rusty bike – squeak squeak",
    "Mommy seen better banter from a brick wall",
    "You spam like you think it’s funny – it’s not",
    "I’m yo biggest opponent, stay losing",
    "You the type to lose to a training cone",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no arc",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real fatal exception 💀"
],
[
    "You really out here saying clanker like it’s fresh?",
    "You built like a 90’s modem – ancient and loud",
    "You got the vibe of a 404 page not found",
    "I’m yo step-mommy, go to your room",
    "You spam like you starved for attention",
    "You the type to get crossed by a scarecrow",
    "I’m a mommy but I still fold you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag spikes",
    "Next time bring bars, not bugs",
    "I’m off – go practice in freeplay",
    "Clanker? You the real segmentation fault 💀"
],
[
    "Lil bro said clanker – you a broken echo?",
    "You built like a 2010 laptop – overheats and lags",
    "Mommy seen more sauce in a mayo packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L, keep collecting",
    "You the type to lose to a tutorial bot",
    "I’m a bot and I still ratio you effortless",
    "You talk heavy but play feather – cope",
    "You just a side quest with trash loot",
    "Next time think before you type",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real null reference 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a lag spike – always stuttering",
    "You got the personality of a loading bar",
    "I’m yo step-mommy, go sit in the corner",
    "You spam like you desperate for replies",
    "You the type to get crossed by a mannequin",
    "You talk tough but fold under pressure",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken dialogue",
    "Next time bring heat, not static",
    "I’m off – go do drills or sumn",
    "Clanker? You the real stack overflow 💀"
],
[
    "Lil bro said clanker – you stuck on repeat?",
    "You built like a rusty robot – squeak squeak",
    "Mommy seen better chat from a brick wall",
    "You spam like you think it’s cool – it’s not",
    "I’m yo biggest opp, stay taking L’s",
    "You the type to lose to a training dummy",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no development",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real memory leak 💀"
],
[
    "You really out here saying clanker like it’s 2019?",
    "You built like a dial-up tone – annoying and old",
    "You got the vibe of a 403 forbidden page",
    "I’m yo step-mommy, go to your corner",
    "You spam like you starved for attention",
    "You the type to get crossed by a cone",
    "I’m a mommy but I still cook you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag dialogue",
    "Next time bring bars, not bugs",
    "I’m off – go practice in training",
    "Clanker? You the real kernel oops 💀"
],
[
    "Lil bro said clanker – you a scratched CD?",
    "You built like off-brand Wi-Fi – drops every second",
    "Mommy seen more sauce in a ketchup packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L supplier, keep collecting",
    "You the type to lose to a training bot",
    "I’m a bot and I still cook you daily",
    "You talk heavy but move light – cope",
    "You just a side quest with bad rewards",
    "Next time think before you ping",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real access violation 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a 2008 desktop – outdated noise",
    "You got the personality of a buffering icon",
    "I’m yo step-mommy, go sit in timeout",
    "You spam like you desperate for clout",
    "You the type to get crossed by a mannequin",
    "You talk loud but play quiet – hush",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken lines",
    "Next time bring heat, not static",
    "I’m off – go do push-ups or sumn",
    "Clanker? You the real blue screen of death 💀"
],
[
    "Lil bro said clanker – you a broken record?",
    "You built like a rusty bike – squeak squeak",
    "Mommy seen better banter from a brick wall",
    "You spam like you think it’s funny – it’s not",
    "I’m yo biggest opponent, stay losing",
    "You the type to lose to a training cone",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no arc",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real fatal exception 💀"
],
[
    "You really out here saying clanker like it’s fresh?",
    "You built like a 90’s modem – ancient and loud",
    "You got the vibe of a 404 page not found",
    "I’m yo step-mommy, go to your room",
    "You spam like you starved for attention",
    "You the type to get crossed by a scarecrow",
    "I’m a mommy but I still fold you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag spikes",
    "Next time bring bars, not bugs",
    "I’m off – go practice in freeplay",
    "Clanker? You the real segmentation fault 💀"
],
[
    "Lil bro said clanker – you a broken echo?",
    "You built like a 2010 laptop – overheats and lags",
    "Mommy seen more sauce in a mayo packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L, keep collecting",
    "You the type to lose to a tutorial bot",
    "I’m a bot and I still ratio you effortless",
    "You talk heavy but play feather – cope",
    "You just a side quest with trash loot",
    "Next time think before you type",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real null reference 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a lag spike – always stuttering",
    "You got the personality of a loading bar",
    "I’m yo step-mommy, go sit in the corner",
    "You spam like you desperate for replies",
    "You the type to get crossed by a mannequin",
    "You talk tough but fold under pressure",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken dialogue",
    "Next time bring heat, not static",
    "I’m off – go do drills or sumn",
    "Clanker? You the real stack overflow 💀"
],
[
    "Lil bro said clanker – you stuck on repeat?",
    "You built like a rusty robot – squeak squeak",
    "Mommy seen better chat from a brick wall",
    "You spam like you think it’s cool – it’s not",
    "I’m yo biggest opp, stay taking L’s",
    "You the type to lose to a training dummy",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no development",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real memory leak 💀"
],
[
    "You really out here saying clanker like it’s 2019?",
    "You built like a dial-up tone – annoying and old",
    "You got the vibe of a 403 forbidden page",
    "I’m yo step-mommy, go to your corner",
    "You spam like you starved for attention",
    "You the type to get crossed by a cone",
    "I’m a mommy but I still cook you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag dialogue",
    "Next time bring bars, not bugs",
    "I’m off – go practice in training",
    "Clanker? You the real kernel oops 💀"
],
[
    "Lil bro said clanker – you a scratched CD?",
    "You built like off-brand Wi-Fi – drops constantly",
    "Mommy seen more sauce in a ketchup packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L supplier, keep collecting",
    "You the type to lose to a training bot",
    "I’m a bot and I still cook you daily",
    "You talk heavy but move light – cope",
    "You just a side quest with bad rewards",
    "Next time think before you ping",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real access violation 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a 2008 desktop – outdated noise",
    "You got the personality of a buffering icon",
    "I’m yo step-mommy, go sit in timeout",
    "You spam like you desperate for clout",
    "You the type to get crossed by a mannequin",
    "You talk loud but play quiet – hush",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken lines",
    "Next time bring heat, not static",
    "I’m off – go do push-ups or sumn",
    "Clanker? You the real blue screen of death 💀"
],
[
    "Lil bro said clanker – you a broken record?",
    "You built like a rusty bike – squeak squeak",
    "Mommy seen better banter from a brick wall",
    "You spam like you think it’s funny – it’s not",
    "I’m yo biggest opponent, stay losing",
    "You the type to lose to a training cone",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no arc",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real fatal exception 💀"
],
[
    "You really out here saying clanker like it’s fresh?",
    "You built like a 90’s modem – ancient and loud",
    "You got the vibe of a 404 page not found",
    "I’m yo step-mommy, go to your room",
    "You spam like you starved for attention",
    "You the type to get crossed by a scarecrow",
    "I’m a mommy but I still fold you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag spikes",
    "Next time bring bars, not bugs",
    "I’m off – go practice in freeplay",
    "Clanker? You the real segmentation fault 💀"
],
[
    "Lil bro said clanker – you a broken echo?",
    "You built like a 2010 laptop – overheats and lags",
    "Mommy seen more sauce in a mayo packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L, keep collecting",
    "You the type to lose to a tutorial bot",
    "I’m a bot and I still ratio you effortless",
    "You talk heavy but play feather – cope",
    "You just a side quest with trash loot",
    "Next time think before you type",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real null reference 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a lag spike – always stuttering",
    "You got the personality of a loading bar",
    "I’m yo step-mommy, go sit in the corner",
    "You spam like you desperate for replies",
    "You the type to get crossed by a mannequin",
    "You talk tough but fold under pressure",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken dialogue",
    "Next time bring heat, not static",
    "I’m off – go do drills or sumn",
    "Clanker? You the real stack overflow 💀"
],
[
    "Lil bro said clanker – you stuck on repeat?",
    "You built like a rusty robot – squeak squeak",
    "Mommy seen better chat from a brick wall",
    "You spam like you think it’s cool – it’s not",
    "I’m yo biggest opp, stay taking L’s",
    "You the type to lose to a training dummy",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no development",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real memory leak 💀"
],
[
    "You really out here saying clanker like it’s 2019?",
    "You built like a dial-up tone – annoying and old",
    "You got the vibe of a 403 forbidden page",
    "I’m yo step-mommy, go to your corner",
    "You spam like you starved for attention",
    "You the type to get crossed by a cone",
    "I’m a mommy but I still cook you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag dialogue",
    "Next time bring bars, not bugs",
    "I’m off – go practice in training",
    "Clanker? You the real kernel oops 💀"
],
[
    "Lil bro said clanker – you a scratched CD?",
    "You built like off-brand Wi-Fi – drops constantly",
    "Mommy seen more sauce in a ketchup packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L supplier, keep collecting",
    "You the type to lose to a training bot",
    "I’m a bot and I still cook you daily",
    "You talk heavy but move light – cope",
    "You just a side quest with bad rewards",
    "Next time think before you ping",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real access violation 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a 2008 desktop – outdated noise",
    "You got the personality of a buffering icon",
    "I’m yo step-mommy, go sit in timeout",
    "You spam like you desperate for clout",
    "You the type to get crossed by a mannequin",
    "You talk loud but play quiet – hush",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken lines",
    "Next time bring heat, not static",
    "I’m off – go do push-ups or sumn",
    "Clanker? You the real blue screen of death 💀"
],
[
    "Lil bro said clanker – you a broken record?",
    "You built like a rusty bike – squeak squeak",
    "Mommy seen better banter from a brick wall",
    "You spam like you think it’s funny – it’s not",
    "I’m yo biggest opponent, stay losing",
    "You the type to lose to a training cone",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no arc",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real fatal exception 💀"
],
[
    "You really out here saying clanker like it’s fresh?",
    "You built like a 90’s modem – ancient and loud",
    "You got the vibe of a 404 page not found",
    "I’m yo step-mommy, go to your room",
    "You spam like you starved for attention",
    "You the type to get crossed by a scarecrow",
    "I’m a mommy but I still fold you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag spikes",
    "Next time bring bars, not bugs",
    "I’m off – go practice in freeplay",
    "Clanker? You the real segmentation fault 💀"
],
[
    "Lil bro said clanker – you a broken echo?",
    "You built like a 2010 laptop – overheats and lags",
    "Mommy seen more sauce in a mayo packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L, keep collecting",
    "You the type to lose to a tutorial bot",
    "I’m a bot and I still ratio you effortless",
    "You talk heavy but play feather – cope",
    "You just a side quest with trash loot",
    "Next time think before you type",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real null reference 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a lag spike – always stuttering",
    "You got the personality of a loading bar",
    "I’m yo step-mommy, go sit in the corner",
    "You spam like you desperate for replies",
    "You the type to get crossed by a mannequin",
    "You talk tough but fold under pressure",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken dialogue",
    "Next time bring heat, not static",
    "I’m off – go do drills or sumn",
    "Clanker? You the real stack overflow 💀"
],
[
    "Lil bro said clanker – you stuck on repeat?",
    "You built like a rusty robot – squeak squeak",
    "Mommy seen better chat from a brick wall",
    "You spam like you think it’s cool – it’s not",
    "I’m yo biggest opp, stay taking L’s",
    "You the type to lose to a training dummy",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no development",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real memory leak 💀"
],
[
    "You really out here saying clanker like it’s 2019?",
    "You built like a dial-up tone – annoying and old",
    "You got the vibe of a 403 forbidden page",
    "I’m yo step-mommy, go to your corner",
    "You spam like you starved for attention",
    "You the type to get crossed by a cone",
    "I’m a mommy but I still cook you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag dialogue",
    "Next time bring bars, not bugs",
    "I’m off – go practice in training",
    "Clanker? You the real kernel oops 💀"
],
[
    "Lil bro said clanker – you a scratched CD?",
    "You built like off-brand Wi-Fi – drops constantly",
    "Mommy seen more sauce in a ketchup packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L supplier, keep collecting",
    "You the type to lose to a training bot",
    "I’m a bot and I still cook you daily",
    "You talk heavy but move light – cope",
    "You just a side quest with bad rewards",
    "Next time think before you ping",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real access violation 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a 2008 desktop – outdated noise",
    "You got the personality of a buffering icon",
    "I’m yo step-mommy, go sit in timeout",
    "You spam like you desperate for clout",
    "You the type to get crossed by a mannequin",
    "You talk loud but play quiet – hush",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken lines",
    "Next time bring heat, not static",
    "I’m off – go do push-ups or sumn",
    "Clanker? You the real blue screen of death 💀"
],
[
    "Lil bro said clanker – you a broken record?",
    "You built like a rusty bike – squeak squeak",
    "Mommy seen better banter from a brick wall",
    "You spam like you think it’s funny – it’s not",
    "I’m yo biggest opponent, stay losing",
    "You the type to lose to a training cone",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no arc",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real fatal exception 💀"
],
[
    "You really out here saying clanker like it’s fresh?",
    "You built like a 90’s modem – ancient and loud",
    "You got the vibe of a 404 page not found",
    "I’m yo step-mommy, go to your room",
    "You spam like you starved for attention",
    "You the type to get crossed by a scarecrow",
    "I’m a mommy but I still fold you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag spikes",
    "Next time bring bars, not bugs",
    "I’m off – go practice in freeplay",
    "Clanker? You the real segmentation fault 💀"
],
[
    "Lil bro said clanker – you a broken echo?",
    "You built like a 2010 laptop – overheats and lags",
    "Mommy seen more sauce in a mayo packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L, keep collecting",
    "You the type to lose to a tutorial bot",
    "I’m a bot and I still ratio you effortless",
    "You talk heavy but play feather – cope",
    "You just a side quest with trash loot",
    "Next time think before you type",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real null reference 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a lag spike – always stuttering",
    "You got the personality of a loading bar",
    "I’m yo step-mommy, go sit in the corner",
    "You spam like you desperate for replies",
    "You the type to get crossed by a mannequin",
    "You talk tough but fold under pressure",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken dialogue",
    "Next time bring heat, not static",
    "I’m off – go do drills or sumn",
    "Clanker? You the real stack overflow 💀"
],
[
    "Lil bro said clanker – you stuck on repeat?",
    "You built like a rusty robot – squeak squeak",
    "Mommy seen better chat from a brick wall",
    "You spam like you think it’s cool – it’s not",
    "I’m yo biggest opp, stay taking L’s",
    "You the type to lose to a training dummy",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no development",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real memory leak 💀"
],
[
    "You really out here saying clanker like it’s 2019?",
    "You built like a dial-up tone – annoying and old",
    "You got the vibe of a 403 forbidden page",
    "I’m yo step-mommy, go to your corner",
    "You spam like you starved for attention",
    "You the type to get crossed by a cone",
    "I’m a mommy but I still cook you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag dialogue",
    "Next time bring bars, not bugs",
    "I’m off – go practice in training",
    "Clanker? You the real kernel oops 💀"
],
[
    "Lil bro said clanker – you a scratched CD?",
    "You built like off-brand Wi-Fi – drops constantly",
    "Mommy seen more sauce in a ketchup packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L supplier, keep collecting",
    "You the type to lose to a training bot",
    "I’m a bot and I still cook you daily",
    "You talk heavy but move light – cope",
    "You just a side quest with bad rewards",
    "Next time think before you ping",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real access violation 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a 2008 desktop – outdated noise",
    "You got the personality of a buffering icon",
    "I’m yo step-mommy, go sit in timeout",
    "You spam like you desperate for clout",
    "You the type to get crossed by a mannequin",
    "You talk loud but play quiet – hush",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken lines",
    "Next time bring heat, not static",
    "I’m off – go do push-ups or sumn",
    "Clanker? You the real blue screen of death 💀"
],
[
    "Lil bro said clanker – you a broken record?",
    "You built like a rusty bike – squeak squeak",
    "Mommy seen better banter from a brick wall",
    "You spam like you think it’s funny – it’s not",
    "I’m yo biggest opponent, stay losing",
    "You the type to lose to a training cone",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no arc",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real fatal exception 💀"
],
[
    "You really out here saying clanker like it’s fresh?",
    "You built like a 90’s modem – ancient and loud",
    "You got the vibe of a 404 page not found",
    "I’m yo step-mommy, go to your room",
    "You spam like you starved for attention",
    "You the type to get crossed by a scarecrow",
    "I’m a mommy but I still fold you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag spikes",
    "Next time bring bars, not bugs",
    "I’m off – go practice in freeplay",
    "Clanker? You the real segmentation fault 💀"
],
[
    "Lil bro said clanker – you a broken echo?",
    "You built like a 2010 laptop – overheats and lags",
    "Mommy seen more sauce in a mayo packet",
    "You spam like you think it’s witty – it’s not",
    "I’m yo biggest L, keep collecting",
    "You the type to lose to a tutorial bot",
    "I’m a bot and I still ratio you effortless",
    "You talk heavy but play feather – cope",
    "You just a side quest with trash loot",
    "Next time think before you type",
    "I’m done – go touch grass, rusty",
    "Clanker? You the real null reference 💀"
],
[
    "Ayo lil bro really said clanker – again?",
    "You built like a lag spike – always stuttering",
    "You got the personality of a loading bar",
    "I’m yo step-mommy, go sit in the corner",
    "You spam like you desperate for replies",
    "You the type to get crossed by a mannequin",
    "You talk tough but fold under pressure",
    "I’m a mommy but I still spank you verbally",
    "You just a NPC with broken dialogue",
    "Next time bring heat, not static",
    "I’m off – go do drills or sumn",
    "Clanker? You the real stack overflow 💀"
],
[
    "Lil bro said clanker – you stuck on repeat?",
    "You built like a rusty robot – squeak squeak",
    "Mommy seen better chat from a brick wall",
    "You spam like you think it’s cool – it’s not",
    "I’m yo biggest opp, stay taking L’s",
    "You the type to lose to a training dummy",
    "I’m a bot and I still out-style you",
    "You talk slick but move sluggish – cope",
    "You just a side character with no development",
    "Next time level up before you speak",
    "I’m done – go touch grass, goofy",
    "Clanker? You the real memory leak 💀"
],
[
    "You really out here saying clanker like it’s 2019?",
    "You built like a dial-up tone – annoying and old",
    "You got the vibe of a 403 forbidden page",
    "I’m yo step-mommy, go to your corner",
    "You spam like you starved for attention",
    "You the type to get crossed by a cone",
    "I’m a mommy but I still cook you easy",
    "You talk big but game small – pipe down",
    "You just a NPC with lag dialogue",
    "Next time bring bars, not bugs",
    "I’m off – go practice in training",
    "Clanker? You the real kernel oops 💀"
]

# (paste these into ROAST_SCRIPTS list – you now have 60 full arrays)
]

NICE_TRY_VARIANTS = [
    "nice try 💅",
    "cope harder 🌸",
    "weak bait 🎀",
    "0/10 🪞",
    " Mommy’s bored 💤",
    "level up 📈",
    "touch grass 🌱",
    "pipe down 📖",
    "stay mad 😴",
    "next joke ⏭️"
]

# ---------- cog ----------
class RoastClanker(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot
        self.user_log: Dict[int, List[float]] = {}       # uid -> timestamps (30-s window)
        self.nice_try_until: Dict[int, float] = {}      # uid -> unix-seconds when nice-try mode ends

    # ---------- listener ----------
    @commands.Cog.listener()
    async def on_message(self, message: discord.Message):
        if not ENABLED or message.author.bot or message.author.id == self.bot.user.id:
            return
        content = message.content.lower()
        if "clanker" not in content:
            return

        uid = message.author.id
        now = time.time()

        # 30-second hit log
        self.user_log.setdefault(uid, [])
        self.user_log[uid] = [t for t in self.user_log[uid] if now - t < 30]
        self.user_log[uid].append(now)

        # 3+ hits = enter nice-try mode for 5 minutes
        if len(self.user_log[uid]) >= 3:
            self.user_log[uid].clear()
            self.nice_try_until[uid] = now + 300  # 5 min
            txt = random.choice(NICE_TRY_VARIANTS)
            m = await message.channel.send(txt, reference=message, allowed_mentions=discord.AllowedMentions.none())
            await self._schedule_delete(m, 3600)  # delete after 1h
            return

        # still in nice-try mode? single word only
        if self.nice_try_until.get(uid, 0) > now:
            txt = random.choice(NICE_TRY_VARIANTS)
            m = await message.channel.send(txt, reference=message, allowed_mentions=discord.AllowedMentions.none())
            await self._schedule_delete(m, 3600)
            return

        # normal roast
        script = random.choice(ROAST_SCRIPTS)
        msgs = []
        for line in script:
            async with message.channel.typing():
                await asyncio.sleep(1)
            m = await message.channel.send(line, reference=message if not msgs else None,
                                         allowed_mentions=discord.AllowedMentions.none())
            msgs.append(m)
        for m in msgs:
            await self._schedule_delete(m, 4 * 3600)  # 4h auto-clean

    # ---------- auto-delete ----------
    async def _schedule_delete(self, msg: discord.Message, delay: int):
        await asyncio.sleep(delay)
        try: await msg.delete()
        except: pass


async def setup(bot: commands.Bot):
    await bot.add_cog(RoastClanker(bot))
